default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: aaa
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: escola_development

test:
  <<: *default
  database: escola_test

production:
  <<: *default
  database: heroku_0c42c1dee736e30
  pool: 5
  username: bfe2eff549076e
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /tmp/mysql.sock
